####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  #external_url: !secret external_url
  internal_url: http://192.168.50.110:8123
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  currency: SEK
  country: SE
  time_zone: Europe/Stockholm
  packages: !include_dir_named include
  allowlist_external_dirs:
    - /config/

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

config:

energy:

backup:

person:

mobile_app:

media_source:

cloud:

my:

#http:
#  ssl_certificate: ssl/fullchain.pem
#  ssl_key: ssl/privkey.pem
#  cors_allowed_origins:
#    - https://google.com
#    - https://www.home-assistant.io
#  use_x_forwarded_for: true
#  trusted_proxies:
#    - 10.0.0.200
#    - 172.30.33.0/24
 
#duckdns:
#  domain: mingleberries
#  access_token: !secret duckdns_access_token

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml
  
zha:
  zigpy_config:
    ota:
      ikea_provider: true                        # Auto update Trådfri devices
      ledvance_provider: true                    # Auto update LEDVANCE devices

#https://home-assistant.io/components/logger/
logger:
  default: error
  logs:
    homeassistant.core: error
    homeassistant.components.websocket_api: error
    homeassistant.components.shell_command: fatal
    custom_components.xiaomi_miio_fan: critical
#    homeassistant.components.zwave: debug
#    homeassistant.components.influxdb: debug
#    custom_components.monitor_docker: debug
#    miflora: debug
#    homeassistant.components.sensor.miflora: debug
#    miflora.miflora_poller: debug
#    pydeconz: debug
#    homeassistant.components.deconz: debug
    custom_components.greenely: error
  
monitor_docker:
  - name: Docker
    containers:
      - home-assistant
      - node-red
      - docker-influxdb-grafana
      - mqtt
      - bajzwave
      - valheim-server
      - vrising-server
      - minecraft
    rename:
      home-assistant: "Home Assistant"
      node-red: "Node-RED"
      valheim-server: "Valheim Server"
      vrising-server: "V Rising Server"
    monitored_conditions: [allinone]
    scan_interval: 120
    
#greenely:
#  email: !secret greenely_email
#  password: !secret greenely_password
#  data:
#    - prices
#    - usage
#  show_hourly: true
#  hourly_offset_days: 1
#  time_format: '%Y-%m-%dT%H:%M'
#  date_format: '%Y-%m-%d'

#https://www.home-assistant.io/components/system_health/
system_health:

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/integrations/recorder/
recorder:
  purge_keep_days: 5

#https://home-assistant.io/components/history/
history:

#https://www.home-assistant.io/components/python_script/
python_script:

#https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300

#https://www.home-assistant.io/components/google_assistant/
#google_assistant:
#  project_id: home-assistant-3a3c9
#  report_state: true
#  service_account:
#    private_key: !secret service_account_private_key
#    client_email: !secret service_account_client_email
#  entity_config: !include google_assistant.yaml
#  expose_by_default: false
  
influxdb:
  host: 127.0.0.1
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

fan:
  - platform: xiaomi_miio_fan
    name: Pooh
    host: 192.168.50.125
    token: !secret pooh_token
    model: dmaker.fan.p33
    
  - platform: xiaomi_miio_airpurifier
    name: Mi Air Purifier 2S
    host: 192.168.50.219
    token: !secret purifier_token
    model: zhimi.airpurifier.mc1

#plant:
#  kitty_plant:
#    sensors:
#        moisture: sensor.kitty_plant_moisture
#        battery: sensor.kitty_plant_battery
#        temperature: sensor.kitty_plant_temperature
#        conductivity: sensor.kitty_plant_conductivity
#        brightness: sensor.kitty_plant_light_intensity
#    min_moisture: 20
    
####################################################
#                                                  #
#                       MQTT                       #
#                                                  #
####################################################
    
#mqtt:
  #sensor:
    #- name: "vally cpu temp"
    #  value_template: "{{ value_json.temp }}"
    #  state_topic: "vally/sensor/cputemp"
    #  unit_of_measurement: '°C'
    #  icon: mdi:thermometer
    #- name: "kitty plant"
    #  state_topic: "plantgw/plants/kittyplant/"
    #  icon: mdi:sprout

####################################################
#                                                  #
#      LINKS TO INDIVIDUAL CONFIGURATION FILES     #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
automation: !include automations.yaml
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
