####################################################
#                                                  #
#                 HOME ASSISTANT                   #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  external_url: !secret external_url
  internal_url: http://192.168.1.141:8123
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  currency: SEK
  time_zone: Europe/Stockholm
  packages: !include_dir_named include
  allowlist_external_dirs:
    - /config/

####################################################
#                                                  #
#                     GENERAL                      #
#                                                  #
####################################################

config:

person:

mobile_app:

#https://www.home-assistant.io/integrations/spotify/
spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

browser_mod:
  prefix: "browser_"
  devices:
    a370fd17_97edf076:
      name: engelbrekt
    fb785be7_f75dc2fa:
      name: paddington

http:
  ssl_certificate: ssl/fullchain.pem
  ssl_key: ssl/privkey.pem
  cors_allowed_origins:
    - https://google.com
    - https://www.home-assistant.io
 
duckdns:
  domain: mingleberries
  access_token: !secret duckdns_access_token

#https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml
  
zha:
  zigpy_config:
    ota:
      ikea_provider: true                        # Auto update Trådfri devices
      ledvance_provider: true                    # Auto update LEDVANCE devices

#https://home-assistant.io/components/logger/
logger:
  default: warning
  logs:
    homeassistant.core: error
    homeassistant.components.websocket_api: error
    homeassistant.components.http: warning
    homeassistant.components.http.ban: warning
    homeassistant.components.shell_command: fatal
#    homeassistant.components.zwave: debug
#    homeassistant.components.influxdb: debug
#    custom_components.monitor_docker: debug
#    miflora: debug
#    homeassistant.components.sensor.miflora: debug
#    miflora.miflora_poller: debug
#    pydeconz: debug
#    homeassistant.components.deconz: debug
#    custom_components.greenely: debug
  
monitor_docker:
  - name: Docker
    containers:
      - home-assistant
      - node-red
      - deconz
      - docker-influxdb-grafana
      - mqtt
      - bajzwave
      - valheim-server
      - watchtower
    rename:
      home-assistant: "Home Assistant"
      deconz: DeCONZ
      node-red: "Node-RED"
      valheim-server: "Valheim Server"
    monitored_conditions: [allinone]
    scan_interval: 120

#https://www.home-assistant.io/components/system_health/
system_health:

#https://www.home-assistant.io/components/weather.darksky/
weather:
  - platform: darksky
    api_key: !secret darksky_api_key

#https://home-assistant.io/components/sun/
sun:

#https://www.home-assistant.io/integrations/recorder/
recorder:
  purge_keep_days: 5

#https://home-assistant.io/components/history/
history:

#https://www.home-assistant.io/components/calendar.google/
google:
  client_id: !secret carolin_email_id
  client_secret: !secret carolin_email_secret

#https://www.home-assistant.io/components/python_script/
python_script:

#https://www.home-assistant.io/components/tts/
tts:
  - platform: google_translate
    service_name: google_say
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    base_url: https://mingleberries.duckdns.org

#https://www.home-assistant.io/components/google_assistant/
google_assistant:
  project_id: home-assistant-3a3c9
  report_state: true
  service_account:
    private_key: !secret service_account_private_key
    client_email: !secret service_account_client_email
  entity_config: !include google_assistant.yaml
  expose_by_default: false
  
influxdb:
  host: 127.0.0.1
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

#plant:
#  kitty_plant:
#    sensors:
#        moisture: sensor.kitty_plant_moisture
#        battery: sensor.kitty_plant_battery
#        temperature: sensor.kitty_plant_temperature
#        conductivity: sensor.kitty_plant_conductivity
#        brightness: sensor.kitty_plant_light_intensity
#    min_moisture: 20
  
####################################################
#                                                  #
#                      ARLO                        #
#                                                  #
####################################################

#https://github.com/twrecked/hass-aarlo
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  mode_api: v2

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed

####################################################
#                                                  #
#      LINKS TO INDIVIDUAL CONFIGURATION FILES     #
#                                                  #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
