homeassistant:

    ####################################################
    #                                                  #
    #                    CUSTOMIZE                     #
    #                                                  #
    ####################################################

  customize:
  
    #person
    person.carolin:
      friendly_name: carolin
      entity_picture: /local/lin.png
    person.will:
      friendly_name: will
      entity_picture: /local/will.png
      
    #switch
    switch.stereo:
      friendly_name: stereo
      icon: mdi:speaker
    switch.tv_lights:
      friendly_name: tv lights
      icon: mdi:lightbulb
    switch.kitchen_window:
      friendly_name: kitchen window lights
      icon: mdi:lightbulb
    switch.lounge_window:
      friendly_name: lounge window lights
      icon: mdi:lightbulb
    switch.scene_electricity_price:
      friendly_name: scene_electricity_price_none