sensor:

  - platform: time_date
    display_options:
    - 'time'
    - 'date'
    - 'date_time'
    
  #- platform: systemmonitor
  #  resources:
  #    - type: disk_use_percent
  #      arg: /home
  #    - type: memory_use_percent
  #    - type: processor_use
  #    - type: last_boot
  #  scan_interval: 120

  #- platform: greenely
  #  email: !secret greenely_email
  #  password: !secret greenely_password
  #  daily_usage: true
  #  hourly_usage: true
  #  facility_id: '315790'
  #  prices: true
  #  hourly_offset_days: 2
  #  date_format: '%Y-%m-%d'
  #  
  #- platform: openai_response
  #  api_key: !secret openai_api_key

  #- platform: miflora
  #  mac: 'C4:7C:8D:6A:9D:CC'
  #  name: kitty plant
  #  median: 3
  #  force_update: true
  #  go_unavailable_timeout: 43200
  #  monitored_conditions:
  #    - moisture
  #    - battery

  #- platform: plex_recently_added
  #  host: 192.168.1.141
  #  token: !secret plex_token
  #  
  #- platform: spotcast
    